name: Cypress Tests

on: push

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run dev
          config: baseUrl=http://localhost:3000
          spec: |
            cypress/e2e/accessibility.cy.ts
