name: Cypress Tests

on: push

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run cypress tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          browser: chrome
          start: npm run dev
          config: baseUrl=http://localhost:3000
          spec: |
            cypress/e2e/accessibility.cy.ts
