name: Scheduled Cypress Tests

on:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  scheduled-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config: baseUrl=https://www.startup-nights.ch
          spec: |
            cypress/e2e/mailchimp.cy.ts

      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-result
          path: cypress/results
          retention-days: 1

      - name: cleanup
        run: npx --yes ts-node scripts/cleanup_cypress_tests.ts
        env:
          NEXT_MAILCHIMP_LIST: ${{ secrets.NEXT_MAILCHIMP_LIST }}
          NEXT_MAILCHIMP: ${{ secrets.NEXT_MAILCHIMP }}
